### PR TITLE
On change callback

### PR DESCRIPTION
**Pull request by faisalk08**
On change callback

### CODE REVIEW

**Comment by patosai** [comment]
I'm not entirely sure how I want to do the callback. I was thinking of having not just the selected items, but also the newly selected and removed ones as well.

Also, unit tests would be sweet.

**Comment by faisalk08** [comment]
How about adding an option called onchange and then inserting the following lines after line number 397
      //on change callback
      if (options.onchange)
    	  options.onchange(selected);

Same aproach can be adopted for onremove as well!!

**Comment by patosai** [comment]
I was thinking of having something like

    options.onChange(allSelectedItems, itemsAdded, itemsRemoved);

**Comment by patosai** [comment]
Finally got around to this in f5676bf0d73f7f23664cae3e4c98c74239a7b53d.

**Pull request closed without merging**
